### ISSUE TITLE
How to make style like swinging water

### ISSUE THREAD

**Issue by devandrii128** [power725/bathtub#1]

**Comment by cool725** [comment]
Please reference this css style. This will help for you, hopefully.

// import tainwind css
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";

// import antd styles
@import "~antd/dist/antd.less";


.water-item {
  animation: waterIncrease 2s linear;
  height: 32px;
}

.decrease .water-item {
  animation: waterDecrease 2s linear;
  height: 32px;
}

@keyframes waterIncrease {
  from { height: 0px; }
  to { height: 32px; }
}

@keyframes waterDecrease {
  from { height: 32px; }
  to { height: 0px; }
}

body {
  .bathtub {
    width: 150px;
    height: 150px;
    background: #000;
    overflow: hidden;
    backface-visibility: hidden;
    transform: translate3d(0, 0, 0);

    .fill {
      transform: translate(0, 150px);
      transition: all cubic-bezier(1, 1, 1, 1) 10s;
    }

    .wave-shape {
      animation-name: waveAction;
      animation-iteration-count: infinite;
      animation-timing-function: linear;
      animation-duration: 0.5s;
      width: 300px;
      height: 150px;
      fill: #04ACFF;
    }
  }
}

**Comment by devandrii128** [comment]
Amazing! That's really what I want.
Thanks for your answer.

**Comment by cool725** [comment]
Hope your success in the future.
